# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'DriveQuantTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'DriveKitCore'
  pod 'DriveKitTripAnalysis'
  pod 'DriveKitPermissionsUtilsUI'
  pod 'DriveKitTripSimulator'
  use_frameworks!

  # Pods for DriveQuantTest

  target 'DriveQuantTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DriveQuantTestUITests' do
    # Pods for testing
  end

end
